### PR TITLE
Ship .d.ts declarations

### LINKED ISSUE #13: Types not shipped in dist package?
Hey there, it looks like .d.ts files are missing from the npm package for 0.3.0. 

Likely just an issue of adding `--declaration`  to the prepare step (and ensuring .d.ts files are included in the package).

### PR DESCRIPTION
**Pull request by akx**
Fixes #13 :)

### CODE REVIEW

**Comment by akx** [comment]
Ping @nornagon, could you review this? :)

**Review by nornagon — CHANGES_REQUESTED** [review]
(a) sorry it took me so long to get to this! I was on vacation in December and lost track of things.

(b) yikes, this is four or more changes in a trench coat! can you break it apart? (1) dependency updates, (2) .d.ts exports, (3) changes to the math, (4) extra null checks / strict mode

**Comment by akx** [comment]
@nornagon Hey, yeah, each of those changes is pretty much a separate commit and are reviewable separately :) Would you like me to split them to separate PRs?

**Comment by nornagon** [comment]
@akx yes please!

**Comment by akx** [comment]
@nornagon Sure!

Split into #14 (this), #16 (dependency upgrades) and #17 (strict + fixups)

**Review by nornagon — APPROVED** [review]

**Pull request merged**
